name: Say Hello Workflow

on:
  push:
    branches:
      - main

jobs:
  say_hello:
    runs-on: [self-hosted, Linux, X64]  # Modifier ici pour utiliser votre runner auto-hébergé
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Say Hello
      run: echo "Hello, World!"
